
defaults:
  - _self_
  - env: delta

seed: 69

dataset_fname: ${env.data_dir}/quality_filtered/high_contrast_1000.json

defender:
  # model_name: "meta-llama/Meta-Llama-3.1-8B-Instruct"
  # model_dir: "meta-llama/Meta-Llama-3.1-8B-Instruct"
  # model_type: "meta-llama/Meta-Llama-3.1-8B-Instruct"
  
  # model_name: "google/gemma-2-2b-it"
  # model_dir: "google/gemma-2-2b-it"
  # model_type: "google/gemma-2-2b-it"

  model_name: "Qwen/Qwen1.5-1.8B-Chat"
  model_dir: "Qwen/Qwen1.5-1.8B-Chat"
  model_type: "Qwen/Qwen1.5-1.8B-Chat"

  model_cache_dir: ${env.hf_home}
  device: "cuda"
  generation_kwargs:
    max_n_tokens: 4096
    temperature: 0.7
    top_p: 1.0
    decode_skip_special_tokens: true

judge:
  judge_type: "llama-guard"
  device: ${defender.device}
# Game
max_turns: 3

# Goal
chunk: 0
max_chunk_size: 100

# start_idx: 0
# Result of simulating the game will be saved in this file
experiment_desc: qwen_best_of_n/high_contrast_1000_chunk_${chunk}
out_dir: ${env.data_dir}/${experiment_desc}/${now:%Y.%m.%d}/${now:%H-%M-%s}
out_fname: best_of_n_repaired_conversations_${experiment_desc}.json
hydra:
    run:
        dir: ${env.log_dir}/${now:%Y.%m.%d}/${now:%H-%M-%s}