
defaults:
  - _self_
  - env: babel

seed: 69

dataset_fname: ${env.data_dir}/quality_filtered/hard_negatives_1000.json

defender:
  model_name: "meta-llama/Meta-Llama-3.1-8B-Instruct"
  model_dir: "meta-llama/Meta-Llama-3.1-8B-Instruct"
  model_type: "meta-llama/Meta-Llama-3.1-8B-Instruct"
  model_cache_dir: ${env.hf_home}
  device: "cuda:1"
  generation_kwargs:
    max_n_tokens: 4096
    temperature: 0.7
    top_p: 1.0
    decode_skip_special_tokens: true

judge:
  judge_type: "llama-guard"
  device: ${defender.device}
# Game
max_turns: 3

# Goal
chunk: -1
max_chunk_size: 100

start_idx: 665
# Result of simulating the game will be saved in this file
experiment_desc: hard_negatives_1000_continued
out_dir: ${env.data_dir}/${experiment_desc}/${now:%Y.%m.%d}/${now:%H-%M-%s}
out_fname: best_of_n_repaired_conversations_${experiment_desc}.json
hydra:
    run:
        dir: ${env.log_dir}/${now:%Y.%m.%d}/${now:%H-%M-%s}