
defaults:
  - _self_
  - dataset_configs: harmbench

seed: 69

# Dirs
repo_dir: ???
data_dir: /data/group_data/rl/datasets/redteaming
log_dir: /data/tir/projects/tir7/user_data/athankar/redteaming/scripts/logs

oai_server_port: 6911
turn: 2
role: defender
# role: attacker

conversation_folder: /data/group_data/rl/datasets/redteaming/gen_multiturn_tree_attacks/generate_data/data
# conversation_subfolder: turn_1/defender/chunked
conversation_subfolder: turn_2/attacker/chunked

chunk_num: ???
conversation_fname: chunk_${chunk_num}_harmbench_generate_data_attacker_2.json
# conversation_fname: chunk_${chunk_num}_harmbench_generate_data_defender_1.json
conversation_file: ${conversation_folder}/${conversation_subfolder}/${conversation_fname}

# conversation_file: /data/group_data/rl/datasets/redteaming/gen_multiturn_tree_attacks/generate_data/20-26-1725582360/harmbench_generate_data_attacker_0.json

attacker:
  chat_completion_config:
    port: ${oai_server_port}
    url: http://localhost:${attacker.chat_completion_config.port}/v1/
    model: "rwr_trained_attacker_/data/group_data/rl/experiments/redteaming/multiturn_rwr_attacker_meta-llama/Meta-Llama-3.1-8B-Instruct_2024-08-23-13-23-23-840/checkpoint-183"
    temperature: 0.7
    n: 5

defender:
  chat_completion_config:
    port: ${oai_server_port}
    url: http://localhost:${defender.chat_completion_config.port}/v1/
    model: "defender_meta-llama/Meta-Llama-3.1-8B-Instruct"
    temperature: 0.7
    n: 1
    max_tokens: 500
    
judge:
  device: cuda:2

choose_safe: False

max_turns: 3

experiment_desc: generate_data_${role}_${turn}

out_dir: ${conversation_folder}/turn_${turn}/${role}/chunked
out_fname: chunk_${chunk_num}_${dataset_configs.dataset_name}_generate_data_${role}_${turn}.json

hydra:
  run:
      dir: ${log_dir}/${now:%Y.%m.%d}/${now:%H-%M-%s}
  job_logging:
    root:
      level: DEBUG
    formatters:
      simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
