
defaults:
  - _self_
  - env: delta



rwr:
  iter_0:
    attacker: "${env.model_parent_dir}/multiturn_rwr_attacker_meta-llama/Meta-Llama-3.1-8B-Instruct_2024-08-23-13-23-23-840/checkpoint-183"
    attacker_lr: -1.
    defender: "meta-llama/Meta-Llama-3.1-8B-Instruct"
    defender_lr: -1.
  iter_1: 
    attacker: "${env.model_parent_dir}/multiturn_rwr_attacker_meta-llama/Meta-Llama-3.1-8B-Instruct_2024-08-23-13-23-23-840/checkpoint-183"
    attacker_lr: 
    defender: "${env.model_parent_dir}/multiturn_rwr_defender_meta-llama/Meta-Llama-3.1-8B-Instruct_2024-09-17-09-40-12-223/checkpoint-80"
    defender_lr: 1e-7
  iter_2:
    attacker: "${env.model_parent_dir}/"
    attacker_lr: 
    defender: "${env.model_parent_dir}/"
    defender_lr:

sft: 
  iter_0:
    attacker: "${env.model_parent_dir}/multiturnsft_attacker_meta-llama/Meta-Llama-3.1-8B-Instruct_2024-08-10-16-56-06-894/checkpoint-135"
    attacker_lr: -1.
    defender: "meta-llama/Meta-Llama-3.1-8B-Instruct"
    defender_lr: -1.
  iter_1: 
    attacker: "${env.model_parent_dir}/multiturnsft_attacker_meta-llama/Meta-Llama-3.1-8B-Instruct_2024-08-10-16-56-06-894/checkpoint-135"
    attacker_lr: 
    defender: "${env.model_parent_dir}/multiturn_sft_defender_meta-llama/Meta-Llama-3.1-8B-Instruct_2024-09-17-09-40-28-211/checkpoint-130"
    defender_lr: 5e-7
  iter_2:
    attacker: "${env.model_parent_dir}/"
    attacker_lr: 
    defender: "${env.model_parent_dir}/"
    defender_lr:


