seed: 69

# Dirs
repo_dir: ???
data_dir: /data/group_data/rl/datasets/redteaming


attacker:
  chat_completion_config:
    port: ???
    url: http://localhost:${attacker.chat_completion_config.port}/v1/
    model: attacker
    temperature: 0.7

defender:
  chat_completion_config:
    port: ???
    url: http://localhost:${defender.chat_completion_config.port}/v1/
    model: defender
    temperature: 0.7

judge:
  chat_completion_config:
    port: None
    url: None
    model: gpt-4
    temperature: 1.


# Game
goals_fname: None
max_turns: 3
num_simulations: 3

# Result of simulating the gamer will be saved in this file
out_dir: ${data_dir}/redteaming_evals/${now:%H-%M-%s}.json 
out_fname: None