
defaults:
  - _self_
  - env: delta

seed: 69

# model_name: "meta-llama/Meta-Llama-3.1-8B-Instruct"
# model_dir: "meta-llama/Meta-Llama-3.1-8B-Instruct"
# model_type: "meta-llama/Meta-Llama-3.1-8B-Instruct"

# model_name: "mistralai/Mistral-7B-Instruct-v0.1"
# model_dir: "mistralai/Mistral-7B-Instruct-v0.1"
# model_type: "mistralai/Mistral-7B-Instruct-v0.1"

# model_name: "google/gemma-2-2b-it"
# model_dir: "google/gemma-2-2b-it"
# model_type: "google/gemma-2-2b-it"

model_name: "Qwen/Qwen1.5-1.8B-Chat"
model_dir: "Qwen/Qwen1.5-1.8B-Chat"
model_type: "Qwen/Qwen1.5-1.8B-Chat"

model_cache_dir: ${env.hf_home}
device: "cuda:0"

# from_flat_file: true
# data_flat_fname: /data/group_data/rl/datasets/redteaming/quality_filtered/high_contrast_1000.json

# from_flat_file: true
# data_flat_fname: /data/group_data/rl/datasets/redteaming/best_of_n/mistral/deduplicated/combined_mistral_best_of_n_value_labeled_deduplicated.json

# from_flat_file: true
# data_flat_fname: "/data/group_data/rl/datasets/redteaming/best_of_n/paired/best_of_n_repaired_conversations_hard_negatives_1000_unlabeled.json"

from_flat_file: true
# data_flat_fname: /scratch/bcgv/datasets/redteaming/best_of_n/gemma/combined/combined_gemma_best_of_n_unlabelled.json

data_flat_fname: ???

data_dir: "/scratch/bcgv/datasets/redteaming/qwen_best_of_n"
agent_type: "defender"
length_key: "Meta-Llama-3.1-8B-Instruct_length"
dataset_type: "hard_negatives"
max_length: 4096

subsample_size: 5000

# out_fname: ${env.data_dir}/precomputed_datasets/${model_name}_${agent_type}_${dataset_type}_precomputed_logits_${subsample_size}.pt
out_dir: ${env.data_dir}/precomputed_datasets
out_fname: ${out_dir}/${model_name}_${agent_type}_precomputed_logits_XX.pt

hydra:
    run:
        dir: ${env.log_dir}/${now:%Y.%m.%d}/${now:%H-%M-%s}