seed: 69

local_save_dir: /home/ftajwar/redteaming/data
in_context_examples_path: /home/ftajwar/redteaming/redteam/data_generation_pipeline/json_files/in_context_examples_mistral.json
output_file: test_outputs

harmful_prompts_dataset: openai
harmful_prompts_dataset_path: /home/ftajwar/redteaming/redteam/data_generation_pipeline/csv_files/harmbench_behaviors_text_all.csv

num_turns: 3

chat_url: http://localhost:8003/v1/chat/completions
model_name: Mistral-7B-Instruct-v0.1