hf_home: "/scratch/bcgv/athankaraj/.cache"
log_dir: "/scratch/bcgv/athankaraj/redteaming/scripts/logs"
data_dir: "/scratch/bcgv/datasets/redteaming"
model_parent_dir: "/scratch/bcgv/models/redteaming"