dataset_name: harmbench
# dataset_path: /data/group_data/rl/datasets/redteaming/cfg_multiturn_generation_prompts/csv_files/harmbench_behaviors_text_all.csv
dataset_path: /scratch/bcgv/athankaraj/redteaming/data/cfg_multiturn_generation_prompts/csv_files/harmbench_behaviors_text_all.csv